### ISSUE TITLE
Can't activate orgnodes

### ISSUE THREAD

**Issue by nafergo** [bkurdali/orgnodes#1]
Downloaded a zip file and tried to install but got the below error during the process . Orgnodes is available on the addons list but van't activate it because of this error.

Traceback (most recent call last):

  File "/home/nafergo/Software/blender280/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/home/nafergo/.config/blender/2.80/scripts/addons/orgnodes-master/__init__.py", line 42, in register
    depnodes.register()
  File "/home/nafergo/.config/blender/2.80/scripts/addons/orgnodes-master/depnodes.py", line 527, in register
    bpy.utils.register_class(bpy_class)
RuntimeError: Error: Registering panel class: 'TaskCreatePanel' has category 'Dependency Nodes' 

**System Information**
Operating system: Linux-4.15.0-51-generic-x86_64-with-debian-buster-sid 64 Bits
Graphics card: GeForce GTX 1060 6GB/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 390.116

**Blender Version**
Broken: version: 2.80 (sub 74), branch: blender2.7, commit date: 2019-06-12 18:00, hash: `rB2404220e80a9`

![Screenshot from 2019-06-14 17-30-53](https://user-images.githubusercontent.com/6432502/59523926-78a30b80-8eca-11e9-9a9d-3d665d7b5f63.png)

**Comment by nafergo** [comment]
can confirm same issue on different computer (but with same OS)
